default: &default
  app_url: "http://localhost:3000"
  static_pages:
    home: "http://localhost:3000/static_pages/home"
    help: "http://localhost:3000/static_pages/help"
  signup: "http://localhost:3000/signup"
  login: "http://localhost:3000/login"
  outsideLink:
    railsHomepage: "http://www.railstutorial.org"
    railsHelpPage: "http://www.railstutorial.org/help"
    railsBook: "http://www.railstutorial.org/book"
  email:
    format: "\\A[\\w+\\-.]+@[a-z\\d\\-.]+\\.[a-z]+\\z"
    maxLength: 256
    fromEmail: "noreply@demomailtrap.com"
  userName:
    maxLength: 50
  password:
    minLength: 6
  pagination:
    users: 10
  avatarSize: 50
  resetToken:
    expiration: 2

development:
  <<: *default

# production:
#   <<: *default
#   app_url: 'https://sample-app.com'
#   static_pages:
#     home: 'http://localhost:3000/static_pages/home'
#     help: 'http://localhost:3000/static_pages/help'
